// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

declare namespace Cloudflare {
  interface Env {
    AUTH_SECRET: string;
    CONSUMER_KEY: string;
    CONSUMER_SECRET: string;
    JWT_SECRET: string;
    DB: D1Database;
    CLOUDFLARE_ACCOUNT_ID: string;
    CLOUDFLARE_DATABASE_ID: string;
    CLOUDFLARE_D1_TOKEN: string;
  }
}
interface Env extends Cloudflare.Env {}
