/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/drack.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei';
import { useCustomization } from '../contexts/Customization';

const Rack = (props) => {
  const { nodes, materials } = useGLTF('/models/drack.glb');
  const {design, shelfColor, frameColor} = useCustomization();
  const rusticTextureProps = useTexture({
    map: '/textures/rustic/Wood_027_basecolor.jpg',
    normalMap: '/textures/rustic/Wood_027_normal.jpg',
    roughnessMap: '/textures/rustic/Wood_027_roughness.jpg',
    aoMap: '/textures/rustic/Wood_027_ambientOcclusion.jpg',
    });
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.frame.geometry} material={materials.Material} position={[0, 0.129, -0.021]} rotation={[0, 0, Math.PI / 4]}>
      <meshStandardMaterial {...(frameColor?.name === "Rustic" ? rusticTextureProps  : {}) }  color={frameColor?.name !== "Rustic" ?  frameColor?.color : undefined}/>
      </mesh>
      <mesh geometry={nodes.spaced.geometry}  position={[0.117, 0.247, -0.021]} visible={design=='spaced'}>
        <meshStandardMaterial {...(shelfColor?.name === "Rustic" ? rusticTextureProps  : {}) }   color={shelfColor?.name !== "Rustic" ?  shelfColor?.color : undefined}/>
      </mesh>
      <mesh geometry={nodes.solid.geometry}  position={[0.138, 0.015, -0.024]} visible={design=='solid'}>
        <meshStandardMaterial {...(shelfColor?.name === "Rustic" ? rusticTextureProps  : {}) }   color={shelfColor?.name !== "Rustic" ?  shelfColor?.color : undefined}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/drack.glb')

export default Rack;













